/**
 * Generates the OpenVPN configuration for an Azure P2S connection.
 *
 * The rendered config is written to the 0700 runtime directory and deleted on
 * disconnect. It is treated as secret material because it embeds the
 * serversecret inline as a tls-auth key.
 *
 * What is deliberately *not* in here:
 *   - the Entra access token. It normally reaches OpenVPN over a private
 *     management socket and never touches disk; only on an OpenVPN older than
 *     2.7.2 does it fall back to a 0600 credentials file this config names;
 *   - any route pushed by the gateway, which OpenVPN installs itself from
 *     PUSH_REPLY;
 *   - any TLS key logging directive.
 */

import { azureCompatDirectives } from './azureCompat.ts';
import { OpenP2SError } from '../errors.ts';
import { toOpenVpnStaticKey } from '../profile/serversecret.ts';
import type { AzureVpnProfile } from '../profile/types.ts';

/**
 * How the config gets the token - the only difference between what `connect`
 * runs and what `convert` writes.
 *
 *   management  connect's default; answered from memory, never on disk
 *   file        connect's fallback, and convert's --credentials mode
 *   external    convert's default; no credential directive, so it is portable
 */
/**
 * Quote a value for an OpenVPN configuration file.
 *
 * CLI values - a CA path, a certificate name - are user input, and the config
 * is read by a process running as root, so `--ca $'/tmp/x\nscript-security 2'`
 * would append a directive. A newline cannot be quoted away in OpenVPN's
 * syntax, so it is rejected rather than escaped; whitespace, `#` and `;` are
 * quoted.
 */
export function openVpnValue(value: string, what: string): string {
  // eslint-disable-next-line no-control-regex -- matching control characters is the point
  if (/[\r\n\0\x1b]/.test(value)) {
    throw new OpenP2SError(`${what} contains a control character and cannot go in a config file`, {
      hint: 'A newline there would let an arbitrary OpenVPN directive be appended.',
    });
  }

  if (value.length === 0) {
    throw new OpenP2SError(`${what} is empty`);
  }

  // Quote only when needed, so the common case stays readable.
  if (!/[\s"'#;\\]/.test(value)) {
    return value;
  }
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export type CredentialDelivery =
  | { readonly kind: 'management'; readonly socketPath: string }
  | { readonly kind: 'file'; readonly path: string }
  | { readonly kind: 'external' };

export interface RenderOptions {
  readonly profile: AzureVpnProfile;
  /** How the token reaches OpenVPN. See CredentialDelivery. */
  readonly credentials: CredentialDelivery;
  /**
   * Send the Azure OCC string and peer-info. Off by default; measurement
   * showed it is not required. See src/openvpn/azureCompat.ts.
   */
  readonly azureCompat?: boolean;
  /**
   * A config to keep and run by hand. Only changes the header: a standalone
   * file is not rewritten or deleted, and holds the tls-auth key.
   */
  readonly standalone?: boolean;
  /** Inline the CA, since its path is distribution-specific. */
  readonly inlineCa?: string | undefined;
  /** CA certificate from the system trust store. */
  readonly caPath: string;
  /** OpenVPN verbosity. 3 is enough to detect the milestones we parse for. */
  readonly verb?: number;
  /**
   * Optional certificate name to require, e.g. "*.vpn.azure.com".
   *
   * Off by default to match the behaviour validated against a live gateway.
   * See docs/SECURITY.md: without it, chain validation still applies, but any
   * certificate issued under the same root would be accepted.
   */
  readonly verifyName?: string | undefined;
  /**
   * Probe mode: `dev null`, `route-noexec`, `ifconfig-noexec`, so the run
   * cannot touch the host whatever uid it has. Everything a probe measures is
   * on the control channel and is unaffected.
   */
  readonly probe?: boolean;
}

/**
 * Render the OpenVPN configuration.
 *
 * Directive values go through openVpnValue(), which rejects control
 * characters. Comments carry no interpolated values at all - a newline in one
 * would end the comment and make the rest directives, in a file run as root.
 */
export function renderOpenVpnConfig(options: RenderOptions): string {
  const { profile, credentials, caPath } = options;
  const verb = options.verb ?? 3;

  // Inline beats a path: a referenced file may not exist where the config
  // ends up, and a config that names a missing CA fails confusingly.
  const caDirective = options.inlineCa
    ? ['<ca>', options.inlineCa.trimEnd(), '</ca>']
    : [`ca ${openVpnValue(caPath, 'the CA path')}`];

  const header = options.standalone
    ? [
        '#',
        '# Generated by OpenP2S from an Azure VPN Client profile.',
        '#',
        '# SECRET: this file embeds the profile serversecret as the inline',
        '# tls-auth key. Keep it 0600 and treat it like a private key.',
        '#',
        '# Requires the OpenP2S OpenVPN: a stock build truncates the Entra',
        '# access token and the gateway rejects the session. See the README.',
        '#',
        '',
      ]
    : [
        '#',
        '# Generated by OpenP2S. Do not edit: this file is rewritten on every',
        '# connect and deleted on disconnect.',
        '#',
        '# It embeds the profile tls-auth key, so it lives in the 0700 runtime',
        '# directory on tmpfs and never on persistent storage.',
        '#',
        '',
      ];

  const lines = [
    ...header,
    'client',
    // See RenderOptions.probe: `dev null` is what makes a probe unable to
    // alter the host's network state, rather than merely unlikely to.
    options.probe ? 'dev null' : 'dev tun',
    'proto tcp-client',
    '',
    ...profile.gateways.map((gateway) => `remote ${gateway} ${profile.port}`),
    'nobind',
    'resolv-retry infinite',
    '',
    '# Require the peer certificate to carry the TLS server extended key',
    '# usage, and validate the chain against the system trust store.',
    'remote-cert-tls server',
  ];

  if (options.verifyName) {
    lines.push(`verify-x509-name ${openVpnValue(options.verifyName, '--verify-name')} name`);
  }

  lines.push(
    '',
    '# Azure P2S negotiates AES-256-GCM; pin it rather than leaving the',
    '# negotiation open.',
    'cipher AES-256-GCM',
    'data-ciphers AES-256-GCM',
    'data-ciphers-fallback AES-256-GCM',
    'auth SHA256',
    '',
    '# The Entra access token is short-lived and cannot be renegotiated by',
    '# OpenVPN, so disable renegotiation and forbid caching the credential in',
    '# process memory for reuse.',
    'reneg-sec 0',
    'auth-nocache',
    '',
    ...caDirective,
    '',
  );

  if (credentials.kind === 'management') {
    lines.push(
      '# The username is the literal string AzureAD and the password is the',
      '# Entra access token. OpenP2S supplies both over a private 0600 unix',
      '# socket, using the multi-line base64 form added in OpenVPN 2.7.2, so',
      '# the token is never written to disk, never appears in argv, and never',
      '# enters the environment.',
      'auth-user-pass',
      `management ${openVpnValue(credentials.socketPath, 'the management socket path')} unix`,
      // management-client: OpenVPN connects to the socket we already created
      // at 0600, rather than creating one of its own.
      'management-client',
      'management-query-passwords',
      // Hold until we release, so the management connection is established
      // before any credential is requested.
      'management-hold',
    );
  } else if (credentials.kind === 'file') {
    lines.push(
      '# Username is the literal string AzureAD; the password is the Entra',
      '# access token, read from a file so it never appears in the process',
      '# arguments or the environment.',
      ...(options.standalone
        ? [
            '#',
            '# Create the credentials file yourself and keep it mode 0600. The',
            '# first line is the username, the second the access token.',
          ]
        : ['# The file is 0600 on tmpfs and removed on disconnect.']),
      `auth-user-pass ${openVpnValue(credentials.path, 'the credentials path')}`,
    );
  } else {
    // Portable output: name no credential source at all. Anything else would
    // bake a runtime path into a file meant to be read, copied and diffed.
    lines.push(
      '# Authentication credentials are supplied by OpenP2S at runtime.',
      '#',
      '# The username is the literal string AzureAD and the password is a',
      '# Microsoft Entra access token, which is short-lived and must not be',
      '# stored. `openp2s connect` obtains one and hands it to OpenVPN over a',
      '# private management socket, so it never reaches the filesystem.',
      '#',
      '# To run this config by hand instead, regenerate it with',
      '# `openp2s convert --credentials <path>` and create that file yourself.',
    );
  }

  const azureDirectives = azureCompatDirectives({
    ...(options.azureCompat !== undefined ? { compat: options.azureCompat } : {}),
  });

  if (azureDirectives.length > 0) {
    lines.push(
      '',
      '# Azure Point-to-Site compatibility. Directives rather than environment',
      '# variables, so what is enabled is visible here, is parsed by OpenVPN',
      '# itself, and survives the privilege boundary.',
      ...azureDirectives,
    );
  }

  if (options.probe) {
    lines.push(
      '',
      '# Probe mode. The server may push routes and an address; refuse to act',
      '# on either. Combined with `dev null` above, the exchange is measured',
      '# without any part of it reaching the host.',
      'route-noexec',
      'ifconfig-noexec',
      // A probe is finished once PUSH_REPLY arrives; never sit in a retry
      // loop against the gateway.
      'connect-retry-max 1',
    );
  }

  lines.push(
    '',
    `verb ${verb}`,
    '',
    '# Azure supplies the tls-auth key as <serversecret> in the profile.',
    '# Embedded inline so no second secret file has to be managed.',
    'key-direction 1',
    '',
    '<tls-auth>',
    toOpenVpnStaticKey(profile.serverSecret).trimEnd(),
    '</tls-auth>',
    '',
  );

  return lines.join('\n');
}

/** Username then password. With auth-nocache the token is not retained. */
export function renderCredentials(username: string, accessToken: string): string {
  return `${username}\n${accessToken}\n`;
}
